version: '3'
services:
  postgres:
    image: postgres:10
    restart: unless-stopped
    volumes:
      - postgresdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: invidiousdb
      POSTGRES_PASSWORD: R3p1aceW1thStr0ngPa33word
      POSTGRES_USER: invidious
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
  invidious:
    build:
      context: .
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      POSTGRES_USER: invidious
      POSTGRES_PASS: R3p1aceW1thStr0ngPa33word
      POSTGRES_HOST: postgres
      POSTGRES_DB: invidiousdb
      POSTGRES_PORT: 5432
      INVIDIOUS_DOMAIN: localhost
      INVIDIOUS_REGISTRATION_ENABLED: "true"
      INVIDIOUS_DISABLE_PROXY: "false"
      INVIDIOUS_HTTPS_ONLY: "false"
      INVIDIOUS_FULL_REFRESH: "false"
      INVIDIOUS_CHECK_TABLES: "true"
      INVIDIOUS_CHANNEL_THREADS: 1
      INVIDIOUS_FEED_THREADS: 1
    depends_on:
      - postgres

volumes:
  postgresdata:
