{{- define "invidious.pghost_inject" -}}
{{- if empty .Values.config.db.host -}}
config:
  db:
    host: {{ template "invidious.pghost" . }}
{{- end -}}
{{- end -}}
{{ $_ := mergeOverwrite .Values (include "invidious.pghost_inject" . | fromYaml) -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "invidious.fullname" . }}
  labels:
    app: {{ template "invidious.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
data:
  INVIDIOUS_CONFIG: |
{{ toYaml .Values.config | indent 4 }}
