name: invidious

image:
  repository: quay.io/invidious/invidious
  tag: latest
  pullPolicy: Always

replicaCount: 1

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 16
  targetCPUUtilizationPercentage: 50

service:
  type: ClusterIP
  port: 3000
  #loadBalancerIP:

ingress:
  enabled: false
  annotations: {}
  ingressClassName:
  hosts:
    - host: invidious.mydomain.local
      path: /
  tls:
    - hosts:
      - invidious.mydomain.local
      secretName: my-tls


resources: {}
  #requests:
  #  cpu: 100m
  #  memory: 64Mi
  #limits:
  #  cpu: 800m
  #  memory: 512Mi

securityContext:
  allowPrivilegeEscalation: false
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000

# See https://github.com/bitnami/charts/tree/master/bitnami/postgresql
postgresql:
  enabled: true
  image:
    tag: 13
  auth:
    username: kemal
    password: kemal
    database: invidious
  primary:
    initdb:
      username: kemal
      password: kemal

# Adapted from ../config/config.yml
config:
  channel_threads: 1
  feed_threads: 1
  db:
    user: kemal
    password: kemal
    #-- Leave empty if you use embeded postgresql server
    host:
    port: 5432
    dbname: invidious
  full_refresh: false
  https_only: false
  domain:
  #-- Generate a key using `pwgen 20 1` for example
  hmac_key: CHANGEME
