name: invidious

image:
  repository: quay.io/invidious/invidious
  tag: latest
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

replicaCount: 1

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 16
  targetCPUUtilizationPercentage: 50

service:
  type: ClusterIP
  port: 3000
  # loadBalancerIP:

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # requests:
  #   cpu: 100m
  #   memory: 64Mi
  # limits:
  #   cpu: 800m
  #   memory: 512Mi

podSecurityContext:
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL

nodeSelector: {}

tolerations: []

affinity: {}


# See https://github.com/bitnami/charts/tree/master/bitnami/postgresql
postgresql:
  enabled: true
  image:
    tag: 16
  auth:
    username: kemal
    password: kemal
    database: invidious
  primary:
    initdb:
      username: kemal
      password: kemal
      scriptsConfigMap: invidious-postgresql-init

# Adapted from ../config/config.yml
config:
  db:
    user: kemal
    password: kemal
    host: invidious-postgresql
    port: 5432
    dbname: invidious
  port: 3000
  domain: ""
  https_only: false
  channel_threads: 1
  full_refresh: false
  feed_threads: 1
